const Map<String, String> en = {
  'login': 'Login',
  'register': 'Register new account',
  'username': 'Username',
  'password': 'Password',
  'confirmPassword': 'Confirm password',
  'changePassword': 'Change password',
  'forgotPassword': 'Forgot password?',
  'matchPassword': 'Password does not match',
  'haveAccount': 'Already have an account? Login',
  'noAccount': 'Don\'t have an account? Register',
  'go': 'Go',
  'submit': 'Submit',
  'cancel': 'Cancel',
  'reset': 'Reset',
  'resetPassword': 'Please input your email to reset password',
  'logOut': 'Log out',
  'fieldValidation': 'Field validation error',
  'fieldNull': 'Field can\'t be empty',
  'logOutFailed': 'Logout Failure',
  'retry': 'Retry',
  "settings": "Settings",
  'general': 'General',
  'sharing': 'Sharing',
  'groupFavorite': 'Group with favorites',
  'myAccount': 'My account',
  'accountSettings': 'Account settings',
  'language': 'Language',
  'support': 'Support',
  'reportProblem': 'Report a problem',
  'home': 'Home',
  'scene': 'Scene',
  'notification': 'Notifications',
  'removeSharedDevice': "Remove device sharing for this user",
  'confirm': 'Confirm',
  'listSharedDevices': "List of shared devices",
  'noData': 'No data',
  'sharedWith': 'Shared with',
  'oldPassword': 'Old password',
  'newPassword': 'New password',
  'report': 'Report',
  'tile': 'Tile',
  'enter': 'Enter',
  'content': 'Content',
  'input': 'Input',
  'user': 'user',
  'edit': 'Edit',
  'device': 'Device',
  'name': 'Name',
  'letAddDevice': 'Let\'s add your first device',
  'is': 'is',
  'online': 'Online',
  'offline': 'Offline',
  "delete": "Delete",
  "devices": "Devices",
  "add": "Add",
  "schedule": "Schedule",
  "share": "Share",
  "sensor": "Sensor",
  "node": "Node",
  "valve": "Valve",
  "threshold": "Threshold",
  "humidity": "Humidity",
  "temperature": "Temperature",
  "light": "Light",
  "farm": "Farm",
  "switch": "Switch",
  "lock": "Lock",
  "tracking": "Tracking",
  "gate": "Gate",
  "socket": "Socket",
  "aircon": "Aircon",
  "other": "Other",
  "save": "Save",
  "toDoNotification": "Do you want to do this?",
  'from': 'From',
  "dashboard": "Dashboard",
  "chart": "Chart",
  "history": "History",
  "more": "More",
  "mode": "Mode",
  "manual": "Manual",
  "auto": "Auto",
  "status": "Status",
  "at": "At",
  "date": "Date",
  "monday": "Monday",
  "tuesday": "Tuesday",
  "wednesday": "Wednesday",
  "thursday": "Thursday",
  "friday": "Friday",
  "saturday": "Saturday",
  "sunday": "Sunday",
  "last": "Last",
  "minutes": "minutes",
  "on": "On",
  "off": "Off",
  "new": "new",
  "addNewSchedule": "Add new schedule",
  "configure": "Configure",
  "startAt": "Start at",
  "endAt": "End at",
  "time": "Time",
  "howLong": "How long?",
  "inTheDays": "In the days",
  "irrigation": "Irrigation",
  "excecuteControl": "Execute control",
  "alertDeviceOff": "Device currently is offline\nPlease try again",
  "fanSpeed": "Fan speed",
  "turbo": "Turbo",
  "userGuide": "User guide",
  "search": "Search",
  "energy": "Energy",
  "today": "Today",
  "consumption": "Consumption",
  "thisWeek": "This week",
  "thisMonth": "This month",
  "day": "Day",
  "week": "Week",
  "month": "Month",
  "energyConsumption": "Energy consumption",
  "electric": "Electric",
  "water": "Water",
  "of": "of",
  "in": "in",
  "text1": "Energy consumption in 4 lastest months",
  "text2": 'Energy consumption in 6 lastest week',

  };
