const Map<String, String> vi = {
  'hello': 'Xin chào',
  'multipleLanguage': 'Đa ngôn ngữ',
  'login': 'Đăng nhập',
  'register': 'Đăng ký',
  'username': 'Tên tài khoản',
  'password': 'Mật khẩu',
  'confirmPassword': 'Mật khẩu xác nhận',
  'changePassword': 'Thay đổi mật khẩu',
  'forgotPassword': 'Quên mật khẩu?',
  'matchPassword': 'Mật khẩu không khớp',
  'haveAccount': 'Đã có tài khoản? Đăng nhập',
  'noAccount': 'Chưa có tài khoản? Đăng ký',
  'go': 'Tiếp tục',
  'submit': 'Xác nhận',
  'cancel': 'Hủy',
  'reset': 'Cài lại',
  'resetPassword': 'Vui lòng nhập email để thay đổi mật khẩu',
  'logOut': 'Đăng xuất',
  'logOutFailed': 'Đăng xuất thất bại',
  'retry': 'Thử lại',
  'fieldValidation': 'Trường này không hợp lệ',
  'fieldNull': 'Trường này là bắt buộc',
  "settings": "Cài đặt",
  'general': 'Chung',
  'sharing': 'Đang chia sẻ',
  'groupFavorite': 'Thiết bị yêu thích',
  'myAccount': 'Tài khoản của tôi',
  'accountSettings': 'Cài đặt tài khoản',
  'language': 'Ngôn ngữ',
  'support': 'Hỗ trợ',
  'reportProblem': 'Phản hồi vấn đề',
  'home': 'Trang chủ',
  'scene': 'Ngữ cảnh',
  'notification': 'Thông báo',
  'removeSharedDevice': "Xóa chia sẻ thiết bị với người dùng này",
  'confirm': 'Xác nhận',
  'listSharedDevices': "Danh sách thiết bị đã chia sẻ",
  'noData': 'Không có dữ liệu',
  'sharedWith': 'Được chia sẻ cho ',
  'oldPassword': 'Mật khẩu cũ',
  'newPassword': 'Mật khẩu mới',
  'report': 'Báo cáo',
  'title': 'Tiêu đề',
  'enter': 'Nhập',
  'content': 'Nội dung',
  'input': 'Nhập',
  'user': 'Người dùng',
  'edit': 'Chỉnh sửa',
  'device': 'Thiết bị',
  'name': 'Tên',
  'letAddDevice': 'Hãy tạo thiết bị đầu tiên',
  'is': 'là',
  'online': 'Trực tuyến',
  'offline': 'Ngoại tuyến',
  "delete": "Xóa",
  "devices": "Danh sách thiết bị",
  "add": "Thêm",
  "schedule": "Lập lịch",
  "share": "Chia sẻ",
  "sensor": "Cảm biến",
  "node": "",
  "valve": "Van điều khiển",
  "threshold": "Ngưỡng",
  "humidity": "Độ ẩm",
  "temperature": "Nhiệt độ",
  "light": "Bóng đèn",
  "farm": "Nông trại",
  "switch": "Công tắc",
  "lock": "Khóa cửa",
  "tracking": "Theo dõi",
  "gate": "Cổng điều khiển",
  "socket": "Ổ cắm",
  "aircon": "Điều hòa",
  "other": "Khác",
  "save": "Lưu",
  "toDoNotification": "Bạn có muốn thực hiện điều này?",
  'from': 'Từ',
  "dashboard": "Bảng điều khiển",
  "chart": "Biểu đồ",
  "history": "Lịch sử",
  "more": "Xem thêm",
  "mode": "Chế độ",
  "manual": "Thủ công",
  "auto": "Tự động",
  "status": "Trạng thái",
  "at": "Vào lúc",
  "date": "Ngày",
  "time": "Thời gian",
  "monday": "Thứ hai",
  "tuesday": "Thứ ba",
  "wednesday": "Thứ tư",
  "thursday": "Thứ năm",
  "friday": "Thứ sáu",
  "saturday": "Thứ bảy",
  "sunday": "Chủ nhật",
  "last": "Kéo dài",
  "minutes": "phút",
  "on": "Bật",
  "off": "Tắt",
  "new": "mới",
  "addNewSchedule": "Tạo lập lịch mới",
  "configure": "Thiết lập",
  "startAt": "Bắt đầu lúc",
  "endAt": "Kết thúc lúc",
  "howLong": "Bao lâu?",
  "inTheDays": "Vào ngày",
  "irrigation": "Tưới tiêu",
  "vavle": "Van điều khiển",
  "excecuteControl": "Thực hiện thao tác",
  "alertDeviceOff": "Thiết bị đang ngoại tuyến.\nVui lòng thử lại sau",
  "fanSpeed": "Tốc độ quạt",
  "turbo": "Đổi hướng",
  "userGuide": "Hướng dẫn sử dụng",
  "search": "Tìm kiếm",
  "energy": "Năng lượng",
  "today": "Hôm nay",
  "consumption": "Tiêu thụ",
  "thisWeek": "Tuần này",
  "thisMonth": "Tháng này",
  "day": "Ngày",
  "week": "Tuần",
  "month": "Tháng",
  "energyConsumption": "Tiêu thụ năng lượng",
  "electric": "Điện",
  "water": "Nước",
  "of": "của",
  "in": "trong",
  "text1": "Tiêu thụ năng lượng trong 4 tháng gần đây",
  "text2": 'Tiêu thụ năng lượng trong 6 tuần gần đây',
};
